[package]
name = "ejemplo2"
version = "0.1.0"
authors = ["kali"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron = "0.4.0"
